### ISSUE TITLE
Facades

### ISSUE THREAD

**Issue by pepperfm** [XXXVLSCCCP/Big-Bang#4]
https://github.com/XXXVLSCCCP/Big-Bang/blob/c42f49faf8057b521cfec193809f009b019c85d3/app/Http/Controllers/Api/ProfileController.php#L93

на роутах уже есть middleware и уже юзер при запросах использует токен, поэтому `User::find($id)` не нужен, там уже есть `Auth::user()` или `Auth::id()` если надо

**Comment by TsvetkovA817** [comment]
этот запрос (/profile/id)  планировал для открытия анкеты-профиля произвольного юзера, например, из результатов поиска. для получения профиля текущего - авторизованного юзера есть запрос /user

**Comment by pepperfm** [comment]
просто это одно и то же https://prnt.sc/14j5ef1
выходит что `$profile = Auth::user()`. поэтому ладно. на текущий момент это странно, но раз есть планы и всё тут поменяется, то ок)

**Comment by TsvetkovA817** [comment]
Не этот момент я описал. Здесь - исправлю
